export default {
  background: "#EAF2FB",
  dominantColor: "#2D7DD2",
  $primaryColor: "#F45D01",
  $secondaryColor: "#A2C945",
  $successColor: "#20AC6B",
  $dangerColor: "#AE1E2C",
  $warningColor: "#CC9900",
  $infoColor: "#0AA3C2",
  $backgroundText: "000000",
  $dominantText: "#FFFFFF",
  $primaryText: "#FFFFFF",
  $secondaryText: "#000000",
  $successText: "#FFFFFF",
  $dangerText: "#FFFFFF",
  $warningText: "#000000",
  $infoText: "#FFFFFF",
  };
